# -*- coding: utf-8 -*-
"""Task-04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q3oCebi6R9veojr5U2A4eVxGTz_MQq0n

#SkillCraft Internship Task-4: Traffic Accident Analysis
"""

import kagglehub

path = kagglehub.dataset_download("sobhanmoosavi/us-accidents")

print("Path to dataset files:", path)

import os

print(os.listdir(path))

#Load dataset
import pandas as pd

file_path = os.path.join(path, "US_Accidents_March23.csv")

df = pd.read_csv(file_path, nrows=500000)#dataset is too big to load of approx 7 millon so only 500000 will be considered here

print("Dataset Shape:", df.shape)
display(df.head())

#Checking memory and missing values
print("Dataset Shape:", df.shape)

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum().sort_values(ascending=False).head(20))

#Checking the important columns
print("Start Time:")
print(df["Start_Time"].head())

print("\nWeather Conditions:")
print(df["Weather_Condition"].value_counts().head(10))

print("\nAccident Severity:")
print(df["Severity"].value_counts())

print("\nStates:")
print(df["State"].nunique())
print(df["State"].value_counts().head(10))

#Convert date/time-Start_Time to analyze accidents by hour, day, and month.
df["Start_Time"] = pd.to_datetime(df["Start_Time"], errors="coerce")

df["Hour"] = df["Start_Time"].dt.hour
df["Day"] = df["Start_Time"].dt.day
df["Month"] = df["Start_Time"].dt.month
df["Day_of_Week"] = df["Start_Time"].dt.day_name()

print(df[["Start_Time", "Hour", "Day", "Month", "Day_of_Week"]].head())

#Create time-of-day categories-This will make the analysis easier to understand:
def get_time_period(hour):
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

df["Time_of_Day"] = df["Hour"].apply(get_time_period)

print(df["Time_of_Day"].value_counts())

# Printing its result
print(df[[
    "Start_Time",
    "Hour",
    "Day_of_Week",
    "Time_of_Day",
    "Weather_Condition",
    "Severity"
]].head(10))

#visualization starts here
import matplotlib.pyplot as plt
import seaborn as sns

#Accidents by Time of Day
time_counts = df["Time_of_Day"].value_counts()

plt.figure(figsize=(8, 5))
sns.barplot(x=time_counts.index, y=time_counts.values)

plt.title("Accidents by Time of Day")
plt.xlabel("Time of Day")
plt.ylabel("Number of Accidents")
plt.show()

#Accidents by Hour of Day
hour_counts = df["Hour"].value_counts().sort_index()

plt.figure(figsize=(10, 5))
sns.lineplot(x=hour_counts.index, y=hour_counts.values, marker="o")

plt.title("Accidents by Hour of Day")
plt.xlabel("Hour")
plt.ylabel("Number of Accidents")
plt.xticks(range(0, 24))
plt.grid()
plt.show()

#Accidents by Day of Week
day_order = [
    "Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday", "Sunday"
]

day_counts = df["Day_of_Week"].value_counts().reindex(day_order)

plt.figure(figsize=(10, 5))
sns.barplot(x=day_counts.index, y=day_counts.values)

plt.title("Accidents by Day of Week")
plt.xlabel("Day")
plt.ylabel("Number of Accidents")
plt.xticks(rotation=45)
plt.show()

#op 10 Weather Conditions During Accidents
weather_counts = df["Weather_Condition"].value_counts().head(10)

plt.figure(figsize=(10, 6))
sns.barplot(
    x=weather_counts.values,
    y=weather_counts.index
)

plt.title("Top 10 Weather Conditions During Accidents")
plt.xlabel("Number of Accidents")
plt.ylabel("Weather Condition")
plt.show()

#road_features
road_features = [
    "Junction",
    "Crossing",
    "Traffic_Signal",
    "Stop",
    "Railway",
    "Roundabout",
    "Give_Way",
    "No_Exit"
]

road_counts = df[road_features].sum().sort_values(ascending=False)

print(road_counts)

#visualization of  Road Features
plt.figure(figsize=(10, 6))

sns.barplot(
    x=road_counts.values,
    y=road_counts.index
)

plt.title("Accidents Associated with Road Features")
plt.xlabel("Number of Accidents")
plt.ylabel("Road Feature")
plt.show()

# Accident Severity
weather_severity = pd.crosstab(
    df["Weather_Condition"],
    df["Severity"]
)

weather_severity = weather_severity.loc[
    df["Weather_Condition"].value_counts().head(10).index
]

plt.figure(figsize=(12, 7))

weather_severity.plot(
    kind="bar",
    figsize=(12, 7)
)

plt.title("Accident Severity by Top Weather Conditions")
plt.xlabel("Weather Condition")
plt.ylabel("Number of Accidents")
plt.xticks(rotation=45)
plt.legend(title="Severity")
plt.tight_layout()
plt.show()

#Checked location data
print(df[["Start_Lat", "Start_Lng"]].head())

print("\nMissing Coordinates:")
print(df[["Start_Lat", "Start_Lng"]].isnull().sum())

#create a geographic scatter plot-use
map_data = df[
    ["Start_Lat", "Start_Lng", "Severity"]
].dropna().sample(
    n=min(60000, len(df)),
    random_state=42
)

plt.figure(figsize=(12, 8))

plt.scatter(
    map_data["Start_Lng"],
    map_data["Start_Lat"],
    s=2,
    alpha=0.3
)

plt.title("US Traffic Accident Hotspots")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.show()

#State wise analysis
state_counts = df["State"].value_counts().head(15)

plt.figure(figsize=(10, 7))

sns.barplot(
    x=state_counts.values,
    y=state_counts.index
)

plt.title("Top 15 States by Number of Accidents")
plt.xlabel("Number of Accidents")
plt.ylabel("State")
plt.show()

# Accident severity by time of day
time_severity = pd.crosstab(
    df["Time_of_Day"],
    df["Severity"]
)

time_order = ["Morning", "Afternoon", "Evening", "Night"]
time_severity = time_severity.reindex(time_order)

time_severity.plot(
    kind="bar",
    figsize=(10, 6)
)

plt.title("Accident Severity by Time of Day")
plt.xlabel("Time of Day")
plt.ylabel("Number of Accidents")
plt.xticks(rotation=0)
plt.legend(title="Severity")
plt.tight_layout()
plt.show()

#key findings
# Most common time of day
print("\nMost Common Time of Day:")
print(df["Time_of_Day"].value_counts().idxmax())

# Most common hour
print("\nMost Common Accident Hour:")
print(df["Hour"].value_counts().idxmax())

# Most common day
print("\nMost Common Day:")
print(df["Day_of_Week"].value_counts().idxmax())

# Most common weather condition
print("\nMost Common Weather Condition:")
print(df["Weather_Condition"].value_counts().idxmax())

# Most common severity
print("\nMost Common Severity:")
print(df["Severity"].value_counts().idxmax())

# State with most accidents
print("\nState with Most Accidents:")
print(df["State"].value_counts().idxmax())

# Analysis in Percentages
total_accidents = len(df)

print("Total Accidents Analyzed:", total_accidents)

print("\nTime of Day Distribution:")
print(
    (df["Time_of_Day"].value_counts(normalize=True) * 100)
    .round(2)
)

print("\nSeverity Distribution:")
print(
    (df["Severity"].value_counts(normalize=True) * 100)
    .round(2)
)

df.to_csv("US_Accidents_Processed_Sample.csv", index=False)

print("Processed dataset saved successfully.")